# Generated by Django 5.1.7 on 2025-04-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_remove_profile_picture_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmine',
            name='block',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blockchain.block'),
            preserve_default=False,
        ),
    ]
