# Generated by Django 5.1.7 on 2025-04-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_createmine_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='index',
        ),
    ]
