# Generated by Django 5.1.7 on 2025-04-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_remove_block_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
