# Generated by Django 5.1.7 on 2025-04-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0007_block_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="block",
            name="index",
        ),
    ]
