# Generated by Django 5.2 on 2025-04-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_remove_block_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='', max_length=50),
        ),
    ]
