# Generated by Django 5.2 on 2025-04-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0009_alter_order_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='nonce',
        ),
    ]
