# Generated by Django 5.1.7 on 2025-03-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_remove_order_timestamp_order_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
