# Generated by Django 5.1.7 on 2025-04-02 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_alter_order_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('data', models.TextField()),
                ('hash', models.CharField(blank=True, max_length=64, unique=True)),
            ],
        ),
    ]
